### ISSUE TITLE
String index out of range: -10

### ISSUE THREAD

**Issue by LiDevil** [liujingxing/XmlClassGuard#10]
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':xxxx:xmlClassGuard'.
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -10
	at com.xml.guard.tasks.XmlClassGuardTask.guardXml(XmlClassGuardTask.kt:94)
	at com.xml.guard.tasks.XmlClassGuardTask.handleResDir(XmlClassGuardTask.kt:65)
	at com.xml.guard.tasks.XmlClassGuardTask.execute(XmlClassGuardTask.kt:46)
```

这是什么问题呀，求大佬解答，感激不尽

**Comment by liujingxing** [comment]
`AndroidManifest.xml`文件贴出来看看

**Comment by LiDevil** [comment]
> `AndroidManifest.xml`文件贴出来看看

大佬牛批，我看了manifest文件name写错了
