### ISSUE TITLE
不支持 org.gradle.unsafe.configuration-cache=true

### ISSUE THREAD

**Issue by initialjie** [liujingxing/XmlClassGuard#13]
* Exception is:
org.gradle.configurationcache.ConfigurationCacheProblemsException: Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Plugin 'xml-class-guard': read system property 'user.dir'
  See https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read

官网建议是
To fix this problem, read Gradle properties using [providers.gradleProperty()](https://docs.gradle.org/7.2/javadoc/org/gradle/api/provider/ProviderFactory.html#gradleProperty-java.lang.String-) instead:
def enabled = providers.gradleProperty('some-property').forUseAtConfigurationTime().present

**Comment by initialjie** [comment]
⌄⨉read system property user.dir📋[ ?](https://docs.gradle.org/7.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read)
⌄plugin 'xml-class-guard'
⌄exception stack trace 📋
org.gradle.api.InvalidUserCodeException: Read system property 'user.dir'
	at org.gradle.configurationcache.SystemPropertyAccessListener.systemPropertyQueried(SystemPropertyAccessListener.kt:92)
	at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:83)
	at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:77)
	at org.apache.xerces.impl.XMLEntityManager$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.apache.xerces.impl.XMLEntityManager.getUserDir(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.expandSystemId(Unknown Source)
	at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at groovy.xml.XmlParser.parse(XmlParser.java:189)
	at com.xml.guard.tasks.MoveDirTask.findPackage(MoveDirTask.kt:63)
	at com.xml.guard.tasks.MoveDirTask.<init>(MoveDirTask.kt:28)
	at com.xml.guard.tasks.MoveDirTask_Decorated.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

**Comment by liujingxing** [comment]
当前你可以添加`org.gradle.unsafe.configuration-cache-problems=warn`配置来规避这个问题

**Comment by initialjie** [comment]
> 当前你可以添加`org.gradle.unsafe.configuration-cache-problems=warn`配置来规避这个问题

嗯可以了，多谢
